const PraticFormLocatos = {
	form: 'form#userForm',
	nameLabel: 'label#userName-label',
	firstNameInput: 'input#firstName',
	lastnameInput: 'input#lastName',
	emailLabel: 'label#userEmail-label',
	emailInput: 'input#userEmail',
	genderLabel: 'div#genterWrapper>div',
	maleInput: 'input[type="radio"]#gender-radio-1',
	maleLabel: 'label[for="gender-radio-1"]',
	femaleInput: 'input[type="radio"]#gender-radio-2',
	femaleLabel: 'label[for="gender-radio-2"]',
	otherInput: 'input[type="radio"]#gender-radio-3',
	otherLabel: 'label[for="gender-radio-3"]',
	mobileLabel: 'label#userNumber-label',
	mobileInput: 'input#userNumber',
	dateOfBirthLabel: 'label#dateOfBirth-wrapper',
	dateOfBirthInput: 'input#dateOfBirthInput',
	subjectsLabel: 'label#subjects-label',
	subjectsInput: 'div#subjectsContainer',
	hobbiesLabel: 'label#subjects-label',
	sportsInput: 'input[type="checkbox"]#hobbies-checkbox-1',
	sportsLabel: 'label[for="hobbies-checkbox-1"]',
	readingInput: 'input[type="checkbox"]#hobbies-checkbox-2',
	readingLabel: 'label[for="hobbies-checkbox-2"]',
	musicInput: 'input[type="checkbox"]#hobbies-checkbox-3',
	musicLabel: 'label[for="hobbies-checkbox-3"]',
	pictureLabel: 'label#subjects-label',
	pictureSelectLabel: 'div.form-file > label[for="uploadPicture"]',
	pictureInput: 'div.form-file > input[type="file"]#uploadPicture',
	currentAddressLabel: 'label#currentAddress-label',
	currentAddressInput: 'textarea#currentAddress',
	stateCityLabel: 'label#stateCity-label',
	selectState: 'div#state',
	selectCity: 'div#city',
	btnSubmit: 'button[type="submit"]#submit',
};

export default PraticFormLocatos;
